runtime: nodejs18  # Use Node.js 18 runtime

env: standard
instance_class: F1  # Free tier instance

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  min_instances: 0
  max_instances: 1 